// Generates a puzzle on the device instead of loading one from a bank
// (concept 15.10 — the bank was dropped: generating one puzzle is fast
// enough to do it live, and a PWA has no reason to preload a puzzle it
// won't play). No React import, no network access — see CLAUDE.md's rule
// that `core/` is pure TypeScript.
//
// The depth-1 evaluator this is built on lives in solver.ts, shared with
// the (not yet implemented) hint system per concept 15.3's "ein Modell für
// Generator und Löser".

import { reachable } from './solver'
import type { Operator } from './expression'

export type { Operator }

/** The subset of Settings (concept section 11) that picking a puzzle needs. */
export interface PuzzleSettings {
  numbers: 2 | 3 | 4
  ops: Operator[] // at least one
  /**
   * Which target-magnitude band (concept 15.5, revised by the target-ranges-
   * display round): 0 for every selection with one band, 0–3 (M · L · XL ·
   * XXL) for the ones with four — see BandRow.bands.
   */
  band: 0 | 1 | 2 | 3
  uniqueOnly: boolean
}

export interface Puzzle {
  numbers: number[]
  target: number
  /**
   * The shape of the solution a player is likeliest to find (`(n+n)×n−n`).
   * Set by `nextPuzzle`, so the caller can feed it back as the shape window
   * on the next draw; nothing about a puzzle's identity depends on it.
   */
  pattern?: string
}

/**
 * Sorted numbers and the target — what makes two puzzles "the same" to a
 * player: the same chips and the same goal, whatever order they happened
 * to be drawn in. `history.ts` keeps a window of these; `nextPuzzle`
 * takes that window and draws around it.
 */
export function puzzleSignature(puzzle: Puzzle): string {
  return `${[...puzzle.numbers].sort((a, b) => a - b).join(',')}=${puzzle.target}`
}

const ALL_OPS: Operator[] = ['+', '-', '*', '/']

function opsMask(ops: Operator[]): number {
  return ALL_OPS.reduce((m, op, i) => (ops.includes(op) ? m | (1 << i) : m), 0)
}

interface BandRow {
  total: number
  unique: number
  /** How many of those sit in each band — see uniqueOnlyAvailable. */
  uniqueBands: number[]
  /**
   * One, three or four [lo, hi] target ranges — the target-ranges-display
   * round's revision of concept 15.5, replacing the earlier tertile/
   * operator-floor search entirely. Magnitude only tracks one operator: ×
   * is the one whose reach actually varies with the target size a player
   * asks for (− and ÷ on single digits barely move regardless of where the
   * cut goes), so only a × selection is worth slicing by magnitude at all.
   * Every 2-number selection, and every 3- or 4-number selection without ×,
   * gets a single band covering its whole [min, max] instead.
   *
   * Where a × selection is sliced, the cut points are fixed rather than
   * fitted per selection — "M" 1–50, "L" 51–100, then "XL" 101–250 and an
   * open-ended "XXL" 251–max for 4 numbers, or "XL" 101–150 with no XXL for
   * 3 numbers (negative-result-display round's follow-up, PO decision):
   * measured, everything a 3-number pool holds above 150 is 96–100% pure-×
   * with 0–2 unique solutions, the "only solvable by multiplication" slice
   * not worth a band — while the same measurement for 4 numbers above 300
   * still needs + or − 65–90% of the time with hundreds of unique
   * solutions, so its XXL stays. The 3-number pool is capped at 150 before
   * anything else runs (`total`/`unique` above already exclude what's above
   * it), not merely displayed that way — those targets are never drawn.
   */
  bands: [number, number][]
}

// The 45-row table (concept 15.8/15.10): for every (number count, operator
// subset) selection, how many puzzles exist in total, how many have a
// unique solution, and the [lo,hi] target range of each band. Answers those
// questions from the whole search space, which a single generated draw
// can't — nextPuzzle() only needs it to know where to aim and whether
// uniqueOnly is available (unique === 0 means concept 15.6's switch
// disables itself).
//
// Generated by scripts/generateBandTable.ts — do not hand-edit. 45 rows.
const BAND_TABLE: Record<string, BandRow> = {
  '2-1': { total: 45, unique: 45, uniqueBands: [45], bands: [[2, 18]] },
  '2-2': { total: 36, unique: 36, uniqueBands: [36], bands: [[1, 8]] },
  '2-3': { total: 81, unique: 81, uniqueBands: [81], bands: [[1, 18]] },
  '2-4': { total: 45, unique: 45, uniqueBands: [45], bands: [[1, 81]] },
  '2-5': { total: 89, unique: 88, uniqueBands: [88], bands: [[1, 81]] },
  '2-6': { total: 81, unique: 81, uniqueBands: [81], bands: [[1, 81]] },
  '2-7': { total: 125, unique: 124, uniqueBands: [124], bands: [[1, 81]] },
  '2-8': { total: 23, unique: 23, uniqueBands: [23], bands: [[1, 9]] },
  '2-9': { total: 68, unique: 68, uniqueBands: [68], bands: [[1, 18]] },
  '2-10': { total: 58, unique: 57, uniqueBands: [57], bands: [[1, 9]] },
  '2-11': { total: 103, unique: 102, uniqueBands: [102], bands: [[1, 18]] },
  '2-12': { total: 59, unique: 50, uniqueBands: [50], bands: [[1, 81]] },
  '2-13': { total: 103, unique: 93, uniqueBands: [93], bands: [[1, 81]] },
  '2-14': { total: 94, unique: 84, uniqueBands: [84], bands: [[1, 81]] },
  '2-15': { total: 138, unique: 127, uniqueBands: [127], bands: [[1, 81]] },
  '3-1': { total: 165, unique: 0, uniqueBands: [0], bands: [[3, 27]] },
  '3-2': { total: 385, unique: 61, uniqueBands: [61], bands: [[1, 17]] },
  '3-3': { total: 550, unique: 0, uniqueBands: [0], bands: [[1, 27]] },
  '3-4': { total: 114, unique: 0, uniqueBands: [0, 0, 0], bands: [[1, 50], [51, 100], [101, 150]] },
  '3-5': { total: 982, unique: 345, uniqueBands: [177, 134, 34], bands: [[1, 50], [51, 100], [101, 150]] },
  '3-6': { total: 1097, unique: 322, uniqueBands: [312, 10, 0], bands: [[1, 50], [51, 100], [101, 150]] },
  '3-7': { total: 1920, unique: 581, uniqueBands: [406, 141, 34], bands: [[1, 50], [51, 100], [101, 150]] },
  '3-8': { total: 100, unique: 9, uniqueBands: [9], bands: [[1, 9]] },
  '3-9': { total: 520, unique: 74, uniqueBands: [74], bands: [[1, 27]] },
  '3-10': { total: 621, unique: 130, uniqueBands: [130], bands: [[1, 17]] },
  '3-11': { total: 976, unique: 114, uniqueBands: [114], bands: [[1, 27]] },
  '3-12': { total: 246, unique: 0, uniqueBands: [0, 0, 0], bands: [[1, 50], [51, 100], [101, 150]] },
  '3-13': { total: 1317, unique: 410, uniqueBands: [242, 134, 34], bands: [[1, 50], [51, 100], [101, 150]] },
  '3-14': { total: 1258, unique: 267, uniqueBands: [257, 10, 0], bands: [[1, 50], [51, 100], [101, 150]] },
  '3-15': { total: 2200, unique: 567, uniqueBands: [392, 141, 34], bands: [[1, 50], [51, 100], [101, 150]] },
  '4-1': { total: 495, unique: 0, uniqueBands: [0], bands: [[4, 36]] },
  '4-2': { total: 2222, unique: 65, uniqueBands: [65], bands: [[1, 26]] },
  '4-3': { total: 2717, unique: 0, uniqueBands: [0], bands: [[1, 36]] },
  '4-4': { total: 377, unique: 0, uniqueBands: [0, 0, 0, 0], bands: [[1, 50], [51, 100], [101, 250], [251, 980]] },
  '4-5': { total: 13314, unique: 6316, uniqueBands: [1494, 2043, 2068, 711], bands: [[1, 50], [51, 100], [101, 250], [251, 980]] },
  '4-6': { total: 14777, unique: 4248, uniqueBands: [2335, 658, 802, 453], bands: [[1, 50], [51, 100], [101, 250], [251, 980]] },
  '4-7': { total: 28035, unique: 9384, uniqueBands: [2523, 2977, 2796, 1088], bands: [[1, 50], [51, 100], [101, 250], [251, 980]] },
  '4-8': { total: 218, unique: 0, uniqueBands: [0], bands: [[1, 9]] },
  '4-9': { total: 3484, unique: 792, uniqueBands: [792], bands: [[1, 36]] },
  '4-10': { total: 4806, unique: 638, uniqueBands: [638], bands: [[1, 26]] },
  '4-11': { total: 6354, unique: 362, uniqueBands: [362], bands: [[1, 36]] },
  '4-12': { total: 1134, unique: 0, uniqueBands: [0, 0, 0, 0], bands: [[1, 50], [51, 100], [101, 250], [251, 980]] },
  '4-13': { total: 18555, unique: 7553, uniqueBands: [2623, 2159, 2060, 711], bands: [[1, 50], [51, 100], [101, 250], [251, 980]] },
  '4-14': { total: 16499, unique: 3946, uniqueBands: [2007, 686, 800, 453], bands: [[1, 50], [51, 100], [101, 250], [251, 980]] },
  '4-15': { total: 30661, unique: 9301, uniqueBands: [2416, 3008, 2789, 1088], bands: [[1, 50], [51, 100], [101, 250], [251, 980]] },
}

function bandRow(settings: PuzzleSettings): BandRow {
  const key = `${settings.numbers}-${opsMask(settings.ops)}`
  const row = BAND_TABLE[key]
  if (!row) throw new Error(`puzzles.ts: no band data for ${settings.numbers} numbers, ops "${settings.ops.join('')}"`)
  return row
}

/** [numbers, target] — a puzzle known to have exactly one canonical solution. */
type Exception = [number[], number]

// Concept 15.11's mechanism, generalised: a selection whose whole uniqueOnly
// pool is small enough to ship is shipped, rather than hunted for by blind
// redraw. The whole-number rule made this matter more, not less — `3 Zahlen,
// +÷, groß` went from a pool redraw could find to one it cannot (measured:
// it threw on 40 of 40 attempts), while `4 Zahlen, nur ÷` lost its list
// entirely, because every unique-solution ÷ puzzle at four numbers reaches
// its target through a fraction.
//
// Generated by scripts/generateBandTable.ts — do not hand-edit. 6 selections.
const UNIQUE_EXCEPTIONS: Record<string, Exception[]> = {
  // 3 Zahlen, - — 61 entries
  '3-2': [
    [[1, 1, 1], 1], [[1, 2, 2], 3], [[1, 3, 3], 5], [[1, 4, 4], 7],
    [[1, 5, 5], 9], [[1, 6, 6], 11], [[1, 7, 7], 13], [[1, 8, 8], 15],
    [[1, 9, 9], 17], [[2, 2, 2], 2], [[2, 2, 3], 1], [[2, 3, 3], 4],
    [[2, 4, 4], 6], [[2, 5, 5], 8], [[2, 6, 6], 10], [[2, 7, 7], 12],
    [[2, 8, 8], 14], [[2, 9, 9], 16], [[3, 3, 3], 3], [[3, 3, 4], 2],
    [[3, 3, 5], 1], [[3, 4, 4], 5], [[3, 5, 5], 7], [[3, 6, 6], 9],
    [[3, 7, 7], 11], [[3, 8, 8], 13], [[3, 9, 9], 15], [[4, 4, 4], 4],
    [[4, 4, 5], 3], [[4, 4, 6], 2], [[4, 4, 7], 1], [[4, 5, 5], 6],
    [[4, 6, 6], 8], [[4, 7, 7], 10], [[4, 8, 8], 12], [[4, 9, 9], 14],
    [[5, 5, 5], 5], [[5, 5, 6], 4], [[5, 5, 7], 3], [[5, 5, 8], 2],
    [[5, 5, 9], 1], [[5, 6, 6], 7], [[5, 7, 7], 9], [[5, 8, 8], 11],
    [[5, 9, 9], 13], [[6, 6, 6], 6], [[6, 6, 7], 5], [[6, 6, 8], 4],
    [[6, 6, 9], 3], [[6, 7, 7], 8], [[6, 8, 8], 10], [[6, 9, 9], 12],
    [[7, 7, 7], 7], [[7, 7, 8], 6], [[7, 7, 9], 5], [[7, 8, 8], 9],
    [[7, 9, 9], 11], [[8, 8, 8], 8], [[8, 8, 9], 7], [[8, 9, 9], 10],
    [[9, 9, 9], 9],
  ],
  // 3 Zahlen, / — 9 entries
  '3-8': [
    [[2, 2, 2], 2], [[3, 3, 3], 3], [[4, 4, 4], 4], [[4, 4, 8], 2],
    [[5, 5, 5], 5], [[6, 6, 6], 6], [[7, 7, 7], 7], [[8, 8, 8], 8],
    [[9, 9, 9], 9],
  ],
  // 3 Zahlen, +/ — 74 entries
  '3-9': [
    [[1, 1, 4], 2], [[1, 1, 6], 3], [[1, 1, 8], 4], [[1, 2, 3], 2],
    [[1, 2, 5], 3], [[1, 2, 6], 2], [[1, 2, 7], 4], [[1, 2, 9], 3],
    [[1, 2, 9], 5], [[1, 3, 5], 2], [[1, 3, 8], 2], [[1, 3, 8], 3],
    [[1, 4, 7], 2], [[1, 5, 9], 2], [[2, 2, 4], 3], [[2, 2, 6], 4],
    [[2, 2, 8], 5], [[2, 3, 4], 2], [[2, 3, 5], 4], [[2, 3, 7], 3],
    [[2, 3, 7], 5], [[2, 4, 4], 4], [[2, 4, 6], 2], [[2, 4, 6], 5],
    [[2, 4, 8], 6], [[2, 5, 5], 5], [[2, 5, 7], 6], [[2, 5, 8], 2],
    [[2, 5, 9], 7], [[2, 6, 6], 6], [[2, 6, 8], 7], [[2, 7, 7], 7],
    [[2, 7, 9], 8], [[2, 8, 8], 8], [[2, 9, 9], 9], [[3, 3, 3], 3],
    [[3, 3, 3], 2], [[3, 3, 6], 3], [[3, 3, 9], 4], [[3, 4, 5], 2],
    [[3, 4, 5], 3], [[3, 4, 8], 4], [[3, 4, 9], 3], [[3, 5, 7], 2],
    [[3, 5, 7], 4], [[3, 6, 9], 5], [[3, 7, 8], 5], [[3, 9, 9], 6],
    [[4, 4, 4], 4], [[4, 4, 4], 2], [[4, 4, 8], 2], [[4, 4, 8], 3],
    [[4, 5, 6], 2], [[4, 5, 7], 3], [[4, 6, 6], 3], [[4, 6, 8], 2],
    [[4, 7, 9], 4], [[5, 5, 5], 5], [[5, 5, 5], 2], [[5, 6, 7], 2],
    [[5, 6, 9], 3], [[5, 7, 8], 3], [[5, 7, 9], 2], [[6, 6, 6], 6],
    [[6, 6, 6], 2], [[6, 7, 8], 2], [[6, 9, 9], 3], [[7, 7, 7], 7],
    [[7, 7, 7], 2], [[7, 8, 9], 2], [[8, 8, 8], 8], [[8, 8, 8], 2],
    [[9, 9, 9], 9], [[9, 9, 9], 2],
  ],
  // 3 Zahlen, -/ — 130 entries
  '3-10': [
    [[1, 2, 2], 3], [[1, 2, 2], 2], [[1, 2, 3], 3], [[1, 2, 4], 4],
    [[1, 2, 5], 5], [[1, 2, 6], 6], [[1, 2, 7], 7], [[1, 2, 7], 3],
    [[1, 2, 8], 8], [[1, 2, 9], 9], [[1, 2, 9], 4], [[1, 3, 3], 5],
    [[1, 3, 7], 2], [[1, 4, 4], 7], [[1, 4, 9], 3], [[1, 4, 9], 2],
    [[1, 5, 5], 9], [[1, 6, 6], 11], [[1, 7, 7], 13], [[1, 8, 8], 15],
    [[1, 9, 9], 17], [[2, 2, 3], 1], [[2, 2, 8], 3], [[2, 3, 3], 4],
    [[2, 3, 3], 3], [[2, 3, 4], 2], [[2, 3, 4], 4], [[2, 3, 5], 5],
    [[2, 3, 6], 6], [[2, 3, 7], 7], [[2, 3, 8], 8], [[2, 3, 8], 2],
    [[2, 3, 9], 9], [[2, 3, 9], 3], [[2, 4, 4], 6], [[2, 4, 5], 2],
    [[2, 5, 5], 8], [[2, 5, 9], 3], [[2, 6, 6], 10], [[2, 6, 7], 2],
    [[2, 7, 7], 12], [[2, 7, 8], 2], [[2, 8, 8], 14], [[2, 8, 9], 2],
    [[2, 9, 9], 16], [[3, 3, 4], 2], [[3, 3, 5], 1], [[3, 3, 9], 2],
    [[3, 4, 4], 5], [[3, 4, 4], 4], [[3, 4, 5], 3], [[3, 4, 5], 5],
    [[3, 4, 6], 6], [[3, 4, 7], 7], [[3, 4, 8], 8], [[3, 4, 9], 9],
    [[3, 5, 5], 7], [[3, 5, 8], 4], [[3, 6, 6], 9], [[3, 6, 7], 3],
    [[3, 7, 7], 11], [[3, 7, 8], 3], [[3, 8, 8], 13], [[3, 8, 9], 3],
    [[3, 9, 9], 15], [[4, 4, 5], 3], [[4, 4, 7], 1], [[4, 5, 5], 6],
    [[4, 5, 5], 5], [[4, 5, 6], 4], [[4, 5, 6], 6], [[4, 5, 7], 7],
    [[4, 5, 8], 8], [[4, 5, 9], 9], [[4, 6, 6], 8], [[4, 6, 7], 4],
    [[4, 6, 7], 2], [[4, 7, 7], 10], [[4, 7, 8], 4], [[4, 7, 9], 3],
    [[4, 8, 8], 12], [[4, 8, 8], 2], [[4, 8, 9], 4], [[4, 9, 9], 14],
    [[5, 5, 6], 4], [[5, 5, 7], 3], [[5, 5, 8], 2], [[5, 5, 9], 1],
    [[5, 6, 6], 7], [[5, 6, 6], 6], [[5, 6, 7], 5], [[5, 6, 7], 3],
    [[5, 6, 7], 7], [[5, 6, 8], 2], [[5, 6, 8], 8], [[5, 6, 9], 9],
    [[5, 7, 7], 9], [[5, 7, 8], 5], [[5, 8, 8], 11], [[5, 8, 9], 5],
    [[5, 8, 9], 2], [[5, 8, 9], 3], [[5, 9, 9], 13], [[6, 6, 7], 5],
    [[6, 6, 8], 4], [[6, 6, 8], 3], [[6, 6, 9], 3], [[6, 6, 9], 2],
    [[6, 7, 7], 8], [[6, 7, 7], 7], [[6, 7, 8], 6], [[6, 7, 8], 8],
    [[6, 7, 9], 3], [[6, 7, 9], 9], [[6, 8, 8], 10], [[6, 8, 8], 4],
    [[6, 8, 9], 6], [[6, 9, 9], 12], [[6, 9, 9], 3], [[7, 7, 8], 6],
    [[7, 7, 9], 5], [[7, 8, 8], 9], [[7, 8, 8], 8], [[7, 8, 9], 7],
    [[7, 8, 9], 4], [[7, 8, 9], 9], [[7, 9, 9], 11], [[8, 8, 9], 7],
    [[8, 9, 9], 10], [[8, 9, 9], 9],
  ],
  // 3 Zahlen, +-/ — 114 entries
  '3-11': [
    [[1, 1, 6], 3], [[1, 1, 8], 4], [[1, 2, 3], 3], [[1, 2, 4], 4],
    [[1, 2, 5], 5], [[1, 2, 6], 6], [[1, 2, 7], 7], [[1, 2, 7], 3],
    [[1, 2, 8], 8], [[1, 2, 9], 3], [[1, 2, 9], 9], [[1, 2, 9], 5],
    [[1, 2, 9], 4], [[1, 3, 7], 2], [[1, 3, 8], 2], [[1, 3, 8], 3],
    [[1, 4, 9], 3], [[1, 4, 9], 2], [[1, 5, 9], 2], [[2, 2, 6], 4],
    [[2, 2, 8], 5], [[2, 2, 8], 3], [[2, 3, 4], 4], [[2, 3, 5], 5],
    [[2, 3, 7], 7], [[2, 3, 7], 3], [[2, 3, 7], 5], [[2, 3, 8], 8],
    [[2, 3, 8], 2], [[2, 3, 9], 9], [[2, 3, 9], 3], [[2, 4, 4], 4],
    [[2, 4, 5], 2], [[2, 4, 6], 2], [[2, 4, 6], 5], [[2, 5, 5], 5],
    [[2, 5, 7], 6], [[2, 5, 8], 2], [[2, 5, 9], 3], [[2, 5, 9], 7],
    [[2, 6, 6], 6], [[2, 6, 7], 2], [[2, 6, 8], 7], [[2, 7, 7], 7],
    [[2, 7, 8], 2], [[2, 7, 9], 8], [[2, 8, 8], 8], [[2, 8, 9], 2],
    [[2, 9, 9], 9], [[3, 3, 6], 3], [[3, 3, 9], 4], [[3, 3, 9], 2],
    [[3, 4, 5], 5], [[3, 4, 7], 7], [[3, 4, 8], 8], [[3, 4, 8], 4],
    [[3, 4, 9], 9], [[3, 4, 9], 3], [[3, 5, 7], 2], [[3, 5, 7], 4],
    [[3, 5, 8], 4], [[3, 6, 7], 3], [[3, 6, 9], 5], [[3, 7, 8], 3],
    [[3, 7, 8], 5], [[3, 8, 9], 3], [[4, 4, 4], 2], [[4, 4, 8], 3],
    [[4, 5, 6], 4], [[4, 5, 6], 6], [[4, 5, 6], 2], [[4, 5, 7], 7],
    [[4, 5, 7], 3], [[4, 5, 8], 8], [[4, 5, 9], 9], [[4, 6, 7], 4],
    [[4, 6, 7], 2], [[4, 7, 8], 4], [[4, 7, 9], 3], [[4, 7, 9], 4],
    [[4, 8, 8], 2], [[4, 8, 9], 4], [[5, 5, 5], 2], [[5, 6, 7], 5],
    [[5, 6, 7], 3], [[5, 6, 7], 7], [[5, 6, 7], 2], [[5, 6, 8], 2],
    [[5, 6, 8], 8], [[5, 6, 9], 9], [[5, 6, 9], 3], [[5, 7, 8], 5],
    [[5, 7, 8], 3], [[5, 7, 9], 2], [[5, 8, 9], 5], [[5, 8, 9], 2],
    [[5, 8, 9], 3], [[6, 6, 6], 2], [[6, 6, 8], 3], [[6, 6, 9], 2],
    [[6, 7, 8], 6], [[6, 7, 8], 8], [[6, 7, 8], 2], [[6, 7, 9], 3],
    [[6, 7, 9], 9], [[6, 8, 8], 4], [[6, 8, 9], 6], [[7, 7, 7], 2],
    [[7, 8, 9], 7], [[7, 8, 9], 4], [[7, 8, 9], 9], [[7, 8, 9], 2],
    [[8, 8, 8], 2], [[9, 9, 9], 2],
  ],
  // 4 Zahlen, - — 65 entries
  '4-2': [
    [[1, 1, 1, 1], 2], [[1, 2, 2, 2], 5], [[1, 3, 3, 3], 8], [[1, 4, 4, 4], 11],
    [[1, 5, 5, 5], 14], [[1, 6, 6, 6], 17], [[1, 7, 7, 7], 20], [[1, 8, 8, 8], 23],
    [[1, 9, 9, 9], 26], [[2, 2, 2, 2], 4], [[2, 2, 2, 3], 3], [[2, 2, 2, 5], 1],
    [[2, 3, 3, 3], 7], [[2, 4, 4, 4], 10], [[2, 5, 5, 5], 13], [[2, 6, 6, 6], 16],
    [[2, 7, 7, 7], 19], [[2, 8, 8, 8], 22], [[2, 9, 9, 9], 25], [[3, 3, 3, 3], 6],
    [[3, 3, 3, 4], 5], [[3, 3, 3, 5], 4], [[3, 3, 3, 7], 2], [[3, 3, 3, 8], 1],
    [[3, 4, 4, 4], 9], [[3, 5, 5, 5], 12], [[3, 6, 6, 6], 15], [[3, 7, 7, 7], 18],
    [[3, 8, 8, 8], 21], [[3, 9, 9, 9], 24], [[4, 4, 4, 4], 8], [[4, 4, 4, 5], 7],
    [[4, 4, 4, 6], 6], [[4, 4, 4, 7], 5], [[4, 4, 4, 9], 3], [[4, 5, 5, 5], 11],
    [[4, 6, 6, 6], 14], [[4, 7, 7, 7], 17], [[4, 8, 8, 8], 20], [[4, 9, 9, 9], 23],
    [[5, 5, 5, 5], 10], [[5, 5, 5, 6], 9], [[5, 5, 5, 7], 8], [[5, 5, 5, 8], 7],
    [[5, 5, 5, 9], 6], [[5, 6, 6, 6], 13], [[5, 7, 7, 7], 16], [[5, 8, 8, 8], 19],
    [[5, 9, 9, 9], 22], [[6, 6, 6, 6], 12], [[6, 6, 6, 7], 11], [[6, 6, 6, 8], 10],
    [[6, 6, 6, 9], 9], [[6, 7, 7, 7], 15], [[6, 8, 8, 8], 18], [[6, 9, 9, 9], 21],
    [[7, 7, 7, 7], 14], [[7, 7, 7, 8], 13], [[7, 7, 7, 9], 12], [[7, 8, 8, 8], 17],
    [[7, 9, 9, 9], 20], [[8, 8, 8, 8], 16], [[8, 8, 8, 9], 15], [[8, 9, 9, 9], 19],
    [[9, 9, 9, 9], 18],
  ],
}

function exceptionList(settings: PuzzleSettings): Exception[] | null {
  return UNIQUE_EXCEPTIONS[`${settings.numbers}-${opsMask(settings.ops)}`] ?? null
}

function randomNumbers(count: number): number[] {
  return Array.from({ length: count }, () => 1 + Math.floor(Math.random() * 9))
}

function pickRandom<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)]
}

// checkNextPuzzle.mjs measured the retry loop below across all 45
// selections: without uniqueOnly, worst case stays in the low double
// digits. "3 Zahlen, nur ÷" is the one uniqueOnly selection without an
// exception list (concept 15.11) and needs real headroom: run against this
// exact nextPuzzle(), 20,000 calls failed 303/20,000 (1.5%) at a cap of
// 200, 49/20,000 (0.25%) at 300 — an earlier, unmeasured guess of "150 is
// enough" was wrong, since 150 is *smaller* than 200 and would have been
// worse — and 1/20,000 (0.005%) at 500. That last number is the real
// residual risk at this cap: small, not zero, and now measured rather than
// assumed.
const MAX_ATTEMPTS = 500

// How many draws that *did* produce a valid puzzle may be spent looking
// for one the player hasn't just seen, before settling for a repeat. The
// window `recent` asks to avoid (history.ts's RECENT_LIMIT) is a wish, not
// a constraint: a selection whose whole in-band pool is smaller than the
// window — two numbers, × and ÷ has 59 puzzles in its entire search space,
// its whole one band — would otherwise loop to MAX_ATTEMPTS and throw, which is
// a far worse outcome than showing a puzzle twice.
//
// The budget is per number count because that is what a draw costs:
// `reachable` runs every permutation × composition × operator tuple, so a
// four-number draw is some two orders of magnitude dearer than a
// two-number one. It is also exactly the other way round from where the
// budget is needed — the thin pools are all two-number selections, while
// no four-number selection has a pool anywhere near the window, so its
// budget is never spent in the first place.
function preferenceAttempts(numbers: PuzzleSettings['numbers']): number {
  return numbers === 4 ? 25 : 250
}

/**
 * How many of the selected operators a puzzle should ideally *need* — the
 * most any single solution could use, which is one per operator position:
 * 1 for two numbers (there is only one position, so the whole question is
 * moot), 2 for three numbers, and up to 3 for four.
 *
 * A preference, never a requirement. Measured exhaustively over the whole
 * search space: with `{+,−}` or `{×,÷}` selected, *no* puzzle at any number
 * count needs both operators — the bracket turns one into the other
 * (`a−(b−c) = a−b+c`, `a÷(b÷c) = a·c÷b`), so 550 of 550 three-number `+−`
 * puzzles and 297 of 297 `×÷` ones are single-operator by construction.
 * And where mixing is possible it is sometimes scarce: `3 Zahlen, +÷,
 * groß` has 20 mixing puzzles against 201 in total. Insisting would either
 * be impossible or would shrink some selections to a pool small enough to
 * bring the repeats back (`4 Zahlen, +−÷, mittel` goes from 3405 puzzles
 * to 30). So the draw asks for this and settles for less.
 */
function preferredDistinctOps(settings: PuzzleSettings): number {
  return Math.min(settings.ops.length, settings.numbers - 1)
}

/**
 * How many distinct operators a puzzle must *need* before the draw will
 * offer it — a floor, replacing the maximum this used to demand.
 *
 * The maximum was added so that picking four operators would not feel like
 * picking one (`5 + 5 + 5 + 5`). It worked, and it was also the single
 * biggest cause of the monotony the product owner reported: demanding three
 * distinct operators from four numbers admits 3 of the 25 shapes the pool
 * holds, which is why 91% of `4 Zahlen, alle vier, groß` came back as
 * `(n+n)×n−n`. A ceiling was the wrong tool; a floor kills `5+5+5+5`
 * outright and leaves 71–97% of each pool intact.
 *
 * Two selections cannot meet a floor of two and are carved out rather than
 * left to starve:
 *  - two numbers, where there is only one operator position at all;
 *  - `{+,−}`, where a−(b−c) = a−b+c stays on the whole numbers, so a
 *    one-operator route always survives. `{×,÷}` used to be carved out for
 *    the same reason and no longer is: its identity a÷(b÷c) = a·c÷b goes
 *    through a fraction, and fractional routes no longer count, so 14% of
 *    three-number and 48% of four-number ×÷ puzzles do need both.
 */
function operatorFloor(settings: PuzzleSettings): number {
  if (settings.numbers < 3 || settings.ops.length < 2) return 1
  if (settings.ops.every(op => op === '+' || op === '-')) return 1
  return 2
}

/** How many puzzles back the draw remembers *shapes*, when the caller keeps a window. */
export const SHAPE_WINDOW = 12

/**
 * A fresh puzzle for these settings, generated on the device (concept
 * 15.10): draw random numbers, ask the solver what's reachable, keep it if
 * the target lands in the selected band, otherwise draw again. The two
 * settings combinations with a thin uniqueOnly pool (concept 15.11) skip
 * the draw loop and pick straight from their exception list instead.
 *
 * `recent` is history.ts's window of recently played puzzles (signatures,
 * see `puzzleSignature`); the draw avoids them where it can. Nothing else
 * about the draw changes, and an empty window is exactly the old
 * behaviour.
 */
export function nextPuzzle(
  settings: PuzzleSettings,
  recent: readonly string[] = [],
  recentShapes: readonly string[] = [],
): Puzzle {
  const row = bandRow(settings)
  const [lo, hi] = row.bands[Math.min(settings.band, row.bands.length - 1)]
  const avoid = new Set(recent)

  if (settings.uniqueOnly) {
    const exceptions = exceptionList(settings)
    if (exceptions) {
      const inBand = exceptions.filter(([, target]) => target >= lo && target <= hi)
      const fresh = inBand.filter(([numbers, target]) => !avoid.has(puzzleSignature({ numbers, target })))
      const [numbers, target] = pickRandom(fresh.length > 0 ? fresh : inBand)
      const shape = reachable(numbers, settings.ops).find(e => e.target === target)
      return { numbers: [...numbers], target, pattern: shape?.pattern }
    }
  }

  // Where each remembered puzzle, and each remembered shape, sits in its
  // window: 0 is longest ago, the last index is the one just played, -1 is
  // one the player has not seen. Lower is better in both, so an unseen
  // puzzle and an unseen shape both score -1.
  const seenAt = new Map(recent.map((signature, i) => [signature, i]))
  const shapeAt = new Map(recentShapes.map((pattern, i) => [pattern, i]))
  const floor = operatorFloor(settings)
  const budget = preferenceAttempts(settings.numbers)
  const relaxEvery = Math.max(1, Math.ceil(budget / 2))
  let asking = floor
  let spent = 0

  interface Candidate { puzzle: Puzzle; seen: number; shape: number; unclean: number; metFloor: boolean }
  // Preference order, lower better: a puzzle the player has not just seen,
  // then a shape they have not just seen, then one that needs the operators
  // asked for, then one that wastes no chip.
  const rank = (c: Candidate): number[] => [c.seen, c.shape, c.metFloor ? 0 : 1, c.unclean]
  let best: Candidate | null = null

  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
    const numbers = randomNumbers(settings.numbers)
    const candidates = reachable(numbers, settings.ops).filter(
      e => e.target >= lo && e.target <= hi &&
        // The whole-number rule is a refusal, not a ranking: a target whose
        // only route runs through 1/81 is not a puzzle for this audience.
        e.wholeSolution &&
        (!settings.uniqueOnly || e.uniqueSolution),
    )
    if (candidates.length === 0) continue

    // Ask for the floor where this draw can meet it, and settle for what it
    // has where it cannot — a draw that offers nothing at the floor is not
    // a reason to throw away the draw.
    const atFloor = candidates.filter(e => e.minDistinctOps >= asking)
    const pool = atFloor.length > 0 ? atFloor : candidates
    const metFloor = atFloor.length > 0

    const scored: Candidate[] = pool.map(e => ({
      puzzle: { numbers, target: e.target, pattern: e.pattern },
      seen: seenAt.get(puzzleSignature({ numbers, target: e.target })) ?? -1,
      shape: shapeAt.get(e.pattern) ?? -1,
      unclean: e.cleanSolution ? 0 : 1,
      metFloor,
    }))
    // The whole point of the change: among candidates that tie on every
    // preference, pick at *random*. Taking the first one — which is what a
    // strict > comparison against a running best does — hands the choice to
    // reachable()'s enumeration order, and that order is fixed: flat
    // arrangements before bracketed ones, operator tuples in + − × ÷ order.
    // Brackets lost every tie by construction.
    let bestKey = rank(scored[0])
    for (const c of scored) {
      const key = rank(c)
      if (lexLess(key, bestKey)) bestKey = key
    }
    const tied = scored.filter(c => lexEqual(rank(c), bestKey))
    const chosen = pickRandom(tied)

    // Nothing better exists than an unseen puzzle in an unseen shape that
    // needs the operators asked for and wastes no chip.
    if (chosen.seen === -1 && chosen.shape === -1 && chosen.metFloor && chosen.unclean === 0) return chosen.puzzle
    if (!best || lexLess(rank(chosen), rank(best))) best = chosen

    spent += 1
    if (spent >= budget) return best.puzzle
    // The floor is unsatisfiable in some bands — `3 Zahlen, +÷, groß` has
    // only 20 puzzles that clear it, against a 30-puzzle history window —
    // so it gives way rather than spending the whole budget hunting.
    if (asking > 1 && spent % relaxEvery === 0) asking = 1
  }

  if (best) return best.puzzle

  throw new Error(
    `nextPuzzle: no candidate found after ${MAX_ATTEMPTS} attempts for ${settings.numbers} numbers, ` +
    `ops "${settings.ops.join('')}", band ${settings.band}${settings.uniqueOnly ? ', uniqueOnly' : ''} — ` +
    'settings.ts should not be offering this combination (concept 15.6/15.9).',
  )
}

/** Lexicographic comparison of two equal-length preference keys, lower being better. */
function lexLess(a: number[], b: number[]): boolean {
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return a[i] < b[i]
  }
  return false
}

function lexEqual(a: number[], b: number[]): boolean {
  return a.every((v, i) => v === b[i])
}

/**
 * Whether concept 15.6's uniqueOnly switch has anything to offer.
 *
 * Band-aware, because a selection can have unique-solution puzzles and a
 * *band* of it have none: `3 Zahlen, +÷` has 74 in all and not one in groß,
 * so leaving the switch on there made nextPuzzle exhaust its attempts and
 * throw — the same class of blank screen `reconcile` was written to prevent,
 * one level further in. Called without a band it answers for the selection
 * as a whole, which is what the panel needs before a band is chosen.
 */
export function uniqueOnlyAvailable(
  numbers: PuzzleSettings['numbers'],
  ops: Operator[],
  band?: number,
): boolean {
  const row = BAND_TABLE[`${numbers}-${opsMask(ops)}`]
  if (row === undefined) return false
  if (band === undefined) return row.unique > 0
  return (row.uniqueBands[Math.min(band, row.uniqueBands.length - 1)] ?? 0) > 0
}

/**
 * The three bands' [lo, hi] target ranges for a selection (concept 15.5) —
 * what the selection panel (concept 15.6) shows under each band chip, and
 * what the header's own summary chip (concept 12.7) shows for the current
 * one. `band`/`uniqueOnly` don't affect which row this reads, so they're
 * fixed placeholders here rather than parameters — every (numbers, ops)
 * pair the 45-row table has an entry for is a valid selection (concept
 * 15.5: "kein einziges Band leer").
 */
export function bandRanges(numbers: PuzzleSettings['numbers'], ops: Operator[]): [number, number][] {
  return bandRow({ numbers, ops, band: 0, uniqueOnly: false }).bands.map(([lo, hi]) => [lo, hi])
}

/**
 * How many bands this selection offers — one, two or three (see BandRow).
 * `useSettings` clamps a stored band against this, since a player can carry
 * band 2 into a selection that has only one.
 */
export function bandCount(numbers: PuzzleSettings['numbers'], ops: Operator[]): number {
  return bandRow({ numbers, ops, band: 0, uniqueOnly: false }).bands.length
}
